import { db } from "./index";
import { people } from "./schema";

export async function seedPeople() {
  console.log("Seeding people...");

  await db.insert(people).values([
    // ── Faculty ──────────────────────────────────────────────────
    { id: "person_arshinder", name: "Dr. Arshinder Kaur", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Supply chain management, sustainability, and demand forecasting researcher." },
    { id: "person_rajendran", name: "Dr. C. Rajendran", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Operations research and last-mile logistics optimization." },
    { id: "person_babji", name: "Dr. Babji Srinivasan", role: "prof", department: "Chemical Engineering", institution: "IIT Madras", bio: "Process systems engineering and AI-driven industrial monitoring." },
    { id: "person_rajagopalan", name: "Dr. Rajagopalan Srinivasan", role: "prof", department: "Chemical Engineering", institution: "IIT Madras", bio: "Digital twins, process control, and virtual simulation." },
    { id: "person_satya", name: "Dr. Satya Chakravarthy", role: "prof", department: "Aerospace Engineering", institution: "IIT Madras", bio: "Drone delivery systems and urban air mobility research." },
    { id: "person_gitakrishnan", name: "Dr. Gitakrishnan Ramadurai", role: "prof", department: "Civil Engineering", institution: "IIT Madras", bio: "Urban mobility, EV charging networks, and transportation systems." },
    { id: "person_anmol", name: "Dr. Anmol Pahwa", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Sustainable last-mile distribution and supply chain resilience." },
    { id: "person_neelesh", name: "Dr. Neelesh Upadhye", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Risk management and electric vehicle logistics optimization." },
    { id: "person_vipin", name: "Dr. Vipin B.", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Revenue management and shipment allocation optimization." },
    { id: "person_usha", name: "Dr. Usha Mohan", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Employee wellness and social lifecycle assessment of logistics." },
    { id: "person_nargis", name: "Dr. Nargis Pervin", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Customer behaviour analysis and NLP for logistics." },
    { id: "person_chandrashekar", name: "Dr. Chandrashekar L.", role: "prof", department: "Computer Science", institution: "IIT Madras", bio: "Reinforcement learning and 3D bin packing optimization." },
    { id: "person_ayon", name: "Dr. Ayon Chakraborty", role: "prof", department: "Computer Science", institution: "IIT Madras", bio: "Wireless navigation and RF-based positioning for warehouses." },
    { id: "person_anil", name: "Dr. Anil Prabhakar", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "Quantum computing and machine learning for logistics." },
    { id: "person_rupesh", name: "Dr. Rupesh Nasre", role: "prof", department: "Computer Science", institution: "IIT Madras", bio: "Parallel computing and scalable CVRP solutions." },
    { id: "person_anuj", name: "Dr. Anuj Kumar Tiwari", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "Model predictive control and EV fleet management." },
    { id: "person_arunkumar", name: "Dr. Arunkumar D. Mahindrakar", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "Control barrier functions and safe robot navigation." },
    { id: "person_bharath", name: "Dr. Bharath Bhikkaji", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "End-to-end logistics optimization and IoT integration." },
    { id: "person_imon", name: "Dr. Imon Chakraborty", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Digital interventions in informal logistics ecosystems." },
    { id: "person_shanti", name: "Dr. K. Shanti Swarup", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "EV fleet coordination and grid-aware charging systems." },
    { id: "person_ganga", name: "Dr. Ganga Prasath S.", role: "prof", department: "Applied Mechanics", institution: "IIT Madras", bio: "Bio-inspired algorithms and decentralized warehouse navigation." },
    { id: "person_sridharakumar", name: "Dr. Sridharakumar Narasimhan", role: "prof", department: "Chemical Engineering", institution: "IIT Madras", bio: "Hybrid optimization and AI for vehicle routing problems." },
    { id: "person_syan", name: "Dr. Syan Gupta", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Network dynamics and misinformation propagation modeling." },
    { id: "person_rahul_m", name: "Dr. Rahul R. Marathe", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Quick commerce sustainability and hyperlocal marketplace design." },
    { id: "person_ramakrishnan", name: "Dr. S. Ramakrishnan", role: "prof", department: "Engineering Design", institution: "IIT Madras", bio: "Driver wellness monitoring using physiological and behavioral data." },
    { id: "person_rachel", name: "Dr. Rachel K. Kalaimani", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "Control systems and supply chain resilience under constraints." },
    { id: "person_lata", name: "Dr. Lata Dayaram", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Worker identity, affect, and wellbeing in logistics." },
    { id: "person_prathamesh", name: "Dr. Prathamesh Vivek Kittur", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Customer emotion intelligence and satisfaction tracking." },
    { id: "person_bharadwaj", name: "Dr. Bharadwaj Satchidanandan", role: "prof", department: "Electrical Engineering", institution: "IIT Madras", bio: "RF-driven navigation and digital twin systems for warehouses." },
    { id: "person_vaibhav", name: "Dr. Vaibhav", role: "prof", department: "Management Studies", institution: "IIT Madras", bio: "Employee wellness and supply chain management." },
    { id: "person_kelitha", name: "Dr. Kelitha Cherian", role: "researcher", department: "Management Studies", institution: "IIT Madras", bio: "Media intelligence and logistics analytics." },
    // ── PhD / Researchers ─────────────────────────────────────────
    { id: "person_vettri", name: "Vettri Velavan J.", role: "researcher", department: "Management Studies", institution: "IIT Madras", bio: "PhD researcher in demand forecasting and vehicle routing." },
    { id: "person_akash", name: "Akash Kale", role: "researcher", department: "Management Studies", institution: "IIT Madras", bio: "PhD researcher in demand analysis and ULD optimization." },
    { id: "person_adnan", name: "Adnan Pasha", role: "researcher", department: "Management Studies", institution: "IIT Madras", bio: "PhD researcher on India's transshipment hub strategy." },
    { id: "person_smriti", name: "Smriti Mishra", role: "researcher", department: "Management Studies", institution: "IIT Madras", bio: "PhD researcher on social lifecycle assessment of logistics." },
    { id: "person_rokom", name: "Rokom Perme", role: "researcher", department: "Civil Engineering", institution: "IIT Madras", bio: "PhD researcher on EV charging network optimization." },
    { id: "person_blessy", name: "Blessy", role: "researcher", department: "Management Studies", institution: "IIT Madras", bio: "PhD researcher on sustainable last-mile distribution." },
    { id: "person_thasnimol", name: "Thasnimol", role: "researcher", department: "Chemical Engineering", institution: "IIT Madras", bio: "PhD researcher on driver monitoring systems." },
    { id: "person_deepak", name: "Deepak", role: "researcher", department: "Chemical Engineering", institution: "IIT Madras", bio: "Post-doctoral researcher on eye-tracking mental health assessment." },
    { id: "person_anish", name: "Anish", role: "researcher", department: "Chemical Engineering", institution: "IIT Madras", bio: "Post-doctoral researcher on AI-driven supply chain platforms." },
    { id: "person_hrushikesh", name: "Hrushikesh", role: "researcher", department: "Electrical Engineering", institution: "IIT Madras", bio: "Quantum algorithms for logistics optimization." },
    { id: "person_datta", name: "Datta Prasad", role: "researcher", department: "Computer Science", institution: "IIT Madras", bio: "Researcher on 3D bin packing and robotic packing." },
    { id: "person_sneh", name: "Sneh Patel", role: "researcher", department: "Computer Science", institution: "IIT Madras", bio: "Parallel computing and CVRP scalability." },
    { id: "person_samrudh", name: "Samrudh R.", role: "researcher", department: "Civil Engineering", institution: "IIT Madras", bio: "MTech researcher on EV charging and mobility planning." },
    // ── MTech / BTech Students ────────────────────────────────────
    { id: "person_varun", name: "Varun Mathivadan", role: "student", department: "Aerospace Engineering", institution: "IIT Madras", bio: "MTech student working on drone delivery feasibility." },
    { id: "person_abirami", name: "Abirami S.", role: "student", department: "Aerospace Engineering", institution: "IIT Madras", bio: "Masters student working on autonomous delivery modules." },
    { id: "person_rohit", name: "Rohit Batra", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on air taxi infrastructure placement." },
    { id: "person_aniruddh", name: "Rama Anirudh", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on urban air mobility optimization." },
    { id: "person_neythra", name: "Neythra Jayaprakash", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on drone-based multi-echelon distribution." },
    { id: "person_sahithi", name: "Kovvali Sahithi", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on multi-echelon drone delivery networks." },
    { id: "person_deepthi", name: "Deepthi Ramesh", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on employee wellness and transshipment." },
    { id: "person_abinav", name: "Abinav", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on employee wellness." },
    { id: "person_omkar", name: "Omkar Nishad", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on customizable demand planning models." },
    { id: "person_shubham", name: "Shubham Gupta", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on logistics startup ecosystem assessment." },
    { id: "person_punith", name: "Punith", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "BS student on electric location routing problem." },
    { id: "person_devanshu", name: "Devanshu", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on electric location routing problem." },
    { id: "person_sajjid", name: "Sajjid", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on electric location routing problem." },
    { id: "person_anish_btech", name: "Anish", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "BTech student on shipment allocation optimization." },
    { id: "person_rishi", name: "Rishi Kannan", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "BTech student on demand planning granularity." },
    { id: "person_alan", name: "Alan Alex Mathew", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "BTech student on customer voice analysis." },
    { id: "person_aditi", name: "Aditi Deo Singh", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on customer email analysis." },
    { id: "person_utsav", name: "Utsav Bhardwaj", role: "student", department: "Management Studies", institution: "IIT Madras", bio: "Masters student on customer voice analysis." },
    { id: "person_wilfred", name: "Wilfred", role: "researcher", department: "Chemical Engineering", institution: "IIT Madras", bio: "Post-doctoral researcher on driver safety systems." },
    { id: "person_pranesh", name: "Pranesh Kannan", role: "student", department: "Chemical Engineering", institution: "IIT Madras", bio: "BTech student on AI-driven supply chain platforms." },
    { id: "person_abulaman", name: "Abulaman", role: "student", department: "Chemical Engineering", institution: "IIT Madras", bio: "BS student on media presence tracking." },
    { id: "person_manish", name: "Manish", role: "student", department: "Chemical Engineering", institution: "IIT Madras", bio: "BS student on media presence tracking." },
    { id: "person_kabilan", name: "Kabilan", role: "student", department: "Chemical Engineering", institution: "IIT Madras", bio: "BTech student on virtual warehouse simulation." },
    { id: "person_rakesh", name: "Rakesh Madhampath", role: "researcher", department: "Chemical Engineering", institution: "IIT Madras", bio: "Researcher on agentic AI reporting systems." },
    { id: "person_syamkumar", name: "Syamkumar K. S.", role: "researcher", department: "Chemical Engineering", institution: "IIT Madras", bio: "Researcher on tech simplification using agentic AI." },
  ]);

  console.log("People seeded.");
}
